# Generated by Django 3.2 on 2020-10-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depute',
            fields=[
                ('identifiant', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
