# Generated by Django 3.2 on 2020-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('identifiant', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
            ],
        ),
    ]
