# Generated by Django 3.2 on 2020-10-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_promulgation',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
