# Generated by Django 3.2 on 2020-10-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dossier_date_promulgation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('identifiant', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=40)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dossier')),
            ],
        ),
    ]
