# Generated by Django 3.2 on 2020-10-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_etape'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='titre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
