# Generated by Django 3.2 on 2020-10-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_etape_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('identifiant', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=16)),
                ('depute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.depute')),
                ('etape', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.etape')),
            ],
        ),
    ]
