# Generated by Django 3.2 on 2020-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
