# Generated by Django 3.2 on 2020-10-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dossier_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='identifiant',
        ),
        migrations.AlterField(
            model_name='vote',
            name='etape',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.etape'),
        ),
    ]
