# Generated by Django 3.2 on 2020-10-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201026_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='etape',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.etape'),
        ),
    ]
