# Generated by Django 3.2 on 2020-10-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201026_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etape'),
        ),
    ]
