# Generated by Django 3.2 on 2020-10-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_etape_code_acte'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='article',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
