# Generated by Django 3.2 on 2020-10-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vote_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='etape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.etape'),
        ),
    ]
