# Generated by Django 3.2 on 2020-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_vote_etape'),
    ]

    operations = [
        migrations.AddField(
            model_name='depute',
            name='actif',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
