# Generated by Django 3.2 on 2020-10-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_depute_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='depute',
            name='groupe',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
