# Generated by Django 3.2 on 2020-10-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_depute_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='article',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='etape',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='url_scrutin',
        ),
        migrations.CreateModel(
            name='Scrutin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=16, null=True)),
                ('url_an', models.CharField(max_length=200)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etape')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='scrutin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.scrutin'),
            preserve_default=False,
        ),
    ]
