# Generated by Django 3.2 on 2020-10-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201030_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutin',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='url_CR',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='url_video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
