# Generated by Django 3.2 on 2020-10-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201030_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutin',
            name='heure',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
