# Generated by Django 3.2 on 2020-11-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_scrutin_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutin',
            name='dossier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dossier'),
        ),
        migrations.AddField(
            model_name='scrutin',
            name='objet',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
