# Generated by Django 3.2 on 2020-11-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201101_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrutin',
            name='etape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.etape'),
        ),
    ]
